### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by boborlarry** [interlark/ustvgo-iptv#21]
There are a few deprecation warnings leading to "Failed to collect link" error
` /Users/admin/ustvgo_downloader/download.py:161: DeprecationWarning: find_element_by_css_selector is deprecated. Please use find_element(by=By.CSS_SELECTOR, value=css_selector) instead`
`/Users/admin/ustvgo_downloader/download.py:109: DeprecationWarning: firefox_profile has been deprecated, please use an Options object`

**Comment by kylep09** [comment]
I think this "Failed to collect link error" is another issue. It looks like the method that is currently used to find the links is broken. Ive forked it myself and made some changes to get it working again. Ill post an issue shortly, followed by a pull request of my fix. 

Are you using this on  linux or windows? I think another part of the issue is the geckodriver download in this script is a few versions behind. I had to update mine manually to version 31 to get this to work.

**Comment by boborlarry** [comment]
I have done some research and I think starting with Selenium 4 they changed the call method.  Caught the geckodriver version as well.

**Comment by kylep09** [comment]
That sounds about right for the Selenium change. If you'd like to see my changes to get it working for now you can find it here.

https://github.com/kylep09/ustvgo_downloader

Im going to try and clean up the deprecation warnings and then continue with the pull request. But functionally its working for now.

**Comment by boborlarry** [comment]
Thank you!  I’ll take a look.

**Comment by interlark** [comment]
New code is not based on browser drivers anymore, so I can mark this driver related issue resolved.
