### ISSUE TITLE
123tv.live

### ISSUE THREAD

**Issue by thekodiak13** [interlark/ustvgo-iptv#34]
Hey -- first of all, outstanding project! I have it running on a Pi 4 with Jellyfin...works great!

I was wondering if there'd be any interest in adding support for '123tv.live' as well. Looking at available channels, it looks like you could add the below to replace the USTVGO channels that require their VPN. I can try to help if needed although I'm by no means a coding expert.

**ESPN** | http://123tv.live/watch/espn-20220618/
**HBO** | http://123tv.live/watch/hbo-02032021/
**Fox Sports 1** | http://123tv.live/watch/fox-sports-1-20220618/
**TNT** | http://123tv.live/watch/tnt/
**VH1** | http://123tv.live/watch/vh1/
**NBC Sports Network** | http://123tv.live/watch/nbcsn-20201106/
**NBA TV** | http://123tv.live/watch/nba-tv-04192021/
**History Channel** | http://123tv.live/watch/history-channel/
**USA Network** | http://123tv.live/watch/usa-network/
**Showtime** | http://123tv.live/watch/showtime/
**BET** | http://123tv.live/watch/bet/
**A&E** | http://123tv.live/watch/ae/

Again, thanks for the great project!

**Comment by Nostradamus1973** [comment]
I just had to jump into this convo.
I'm in agreement with you, @interlark definitely has an outstanding project, I'm running this project on Jellyfin as well and it certainly makes a nice viewing experience for me and my family.
_Personally, I think adding those streams would certainly enrich what @interlark already has_, one would think he could add them to his m3u that we already have in place; _that-being-said, he may not be willing to take on another project because he is preoccupied with other things._
Thx

**Comment by thekodiak13** [comment]
> If you want 123tv, there's a repo that someone has created that is a good start: https://github.com/ParrotDevelopers/123TV

Dude @dahartigan thanks for pointing out that repo...don't know how I missed it.

And I agree everything works nicely as-is. Just figured I'd throw the suggestion out there. If @interlark gets bored and want to fool around with it, cool. If not, that's cool too. The project is already amazing!

Since there's a repo that works with 123tv, @interlark is welcome to close this thread...or I can if people think I should.

**Comment by interlark** [comment]
@thekodiak13 Hi, thanks for this info, I haven't heard of this site. 
Looks like it has IPTV channels, some of them are broadcasted from west russia backends, some of them are broadcasted using P2P (these channels don't work for me, shows no peers in the network).

I agree with @dahartigan that we better not to mix it up to keep it simple, but due to the last USTVGO's rules on non-US IP addresses, I think I can fork this project and adapt it for those channels which are broadcasted from russia.
On the other side, I don't know the count of them, at first look it feels about 10-15, is it worth it?

**Comment by interlark** [comment]
There is https://github.com/interlark/123tv-iptv repo which is a ported version of this repo for [123TV](http://123tv.live/) service. 
Could have potential auth-rotation issues, fix it later. Contains non-P2P channels, P2P channels doesn't work for me anyway.

**Comment by thekodiak13** [comment]
@interlark Awesome! I'll test out the new repo some time this week. Really appreciate your work buddy!

**Comment by interlark** [comment]
Fixed auth key rotation issue in [123tv-iptv](https://github.com/interlark/123tv-iptv), it's stable now. Added link to this port in current repo's readme.

I like that 123TV has bigger video resolution, but it has smaller channels list than USTVGO.

Thanks @thekodiak13  for this info, we've built nice solution for those who hasn't US VPN as 123TV let us watch IPTV from any IP address.

**Comment by thekodiak13** [comment]
You da man @interlark !!!!
